name: Validate for macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-intel:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    strategy:
      matrix:
        os: [macos-13]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        brew install pkg-config go protobuf protoc-gen-go
        make all_wo_orcl
        ls -ltr bin/
        ./bin/schema_gen --help
        ./bin/diff_gen --help
        rm -rf bin
        git checkout schema_gen/schema_gen.go go.mod go.sum
        pushd /tmp
        wget -q https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-basic-macos.x64-19.8.0.0.0dbru.dmg
        wget -q https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-sdk-macos.x64-19.8.0.0.0dbru.dmg
        sudo hdiutil attach instantclient-basic-macos.x64-19.8.0.0.0dbru.dmg
        sudo hdiutil attach instantclient-sdk-macos.x64-19.8.0.0.0dbru.dmg
        cd /Volumes/instantclient-basic-macos.x64-19.8.0.0.0dbru
        ./install_ic.sh
        cd /Volumes/instantclient-sdk-macos.x64-19.8.0.0.0dbru
        ./install_ic.sh
        popd
        cp oci8-macos.pc /Users/runner/Downloads/instantclient_19_8/oci8.pc
        export LD_LIBRARY_PATH=/Users/runner/Downloads/instantclient_19_8:$LD_LIBRARY_PATH
        export DYLD_FALLBACK_LIBRARY_PATH=$LD_LIBRARY_PATH
        export PKG_CONFIG_PATH=/Users/runner/Downloads/instantclient_19_8:$PKG_CONFIG_PATH
        make all
        ls -ltr bin/
        ./bin/schema_gen --help
        ./bin/diff_gen --help
  macos-arm:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        brew install pkg-config go protobuf protoc-gen-go
        make all_wo_orcl
        ls -ltr bin/
        ./bin/schema_gen --help
        ./bin/diff_gen --help
        rm -rf bin
        git checkout schema_gen/schema_gen.go go.mod go.sum
        pushd /tmp
        wget -q https://download.oracle.com/otn_software/mac/instantclient/233023/instantclient-basic-macos.arm64-23.3.0.23.09-1.dmg
        wget -q https://download.oracle.com/otn_software/mac/instantclient/233023/instantclient-sdk-macos.arm64-23.3.0.23.09.dmg
        sudo hdiutil attach instantclient-basic-macos.arm64-23.3.0.23.09-1.dmg
        sudo hdiutil attach instantclient-sdk-macos.arm64-23.3.0.23.09.dmg
        cd /Volumes/instantclient-basic-macos.arm64-23.3.0.23.09
        ./install_ic.sh
        cd /Volumes/instantclient-sdk-macos.arm64-23.3.0.23.09
        ./install_ic.sh
        popd
        cp oci8-macos.pc /Users/runner/Downloads/instantclient_23_3/oci8.pc
        export LD_LIBRARY_PATH=/Users/runner/Downloads/instantclient_23_3:$LD_LIBRARY_PATH
        export DYLD_FALLBACK_LIBRARY_PATH=$LD_LIBRARY_PATH
        export PKG_CONFIG_PATH=/Users/runner/Downloads/instantclient_23_3:$PKG_CONFIG_PATH
        make all
        ls -ltr bin/
        ./bin/schema_gen --help
        ./bin/diff_gen --help
