name: Validate for macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        brew install pkg-config protobuf protoc-gen-go
        pushd /tmp
        wget -q https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-basic-macos.x64-19.8.0.0.0dbru.dmg
        wget -q https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-sdk-macos.x64-19.8.0.0.0dbru.dmg
        sudo hdiutil attach instantclient-basic-macos.x64-19.8.0.0.0dbru.dmg
        sudo hdiutil attach instantclient-sdk-macos.x64-19.8.0.0.0dbru.dmg
        cd /Volumes/instantclient-basic-macos.x64-19.8.0.0.0dbru
        ./install_ic.sh
        cd /Volumes/instantclient-sdk-macos.x64-19.8.0.0.0dbru
        ./install_ic.sh
        popd
        cp oci8-macos.pc /Users/runner/Downloads/instantclient_19_8/oci8.pc
        export LD_LIBRARY_PATH=/Users/runner/Downloads/instantclient_19_8
        export PKG_CONFIG_PATH=/Users/runner/Downloads/instantclient_19_8
        make all
        ls -ltr bin/
        ./bin/schema_gen --help
        ./bin/diff_gen --help
        rm -rf bin
        make all_wo_orcl
        ls -ltr bin/
        ./bin/schema_gen --help
        ./bin/diff_gen --help
